# Generated by Django 3.1.7 on 2021-04-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opening',
            name='embed_code',
            field=models.TextField(default='None'),
        ),
    ]
