# Generated by Django 3.1.7 on 2021-04-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0002_opening_embed_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='opening',
            name='embed_code_lichess',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='opening',
            name='embed_code_lichess_play',
            field=models.TextField(default='None'),
        ),
    ]
