# Generated by Django 3.1.7 on 2021-04-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0003_auto_20210406_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='opening',
            name='description',
            field=models.TextField(default='None'),
        ),
    ]
