# Generated by Django 3.1.7 on 2021-04-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0006_auto_20210411_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opening',
            old_name='embed_code_lichess',
            new_name='embed_code_chess_com',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='embed_code_lichess_play',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='pgn',
        ),
        migrations.AlterField(
            model_name='categoriestypes',
            name='category_type',
            field=models.CharField(default='Default', max_length=200, primary_key=True, serialize=False),
        ),
    ]
